# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transfer_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(575, 395)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.type = QtWidgets.QComboBox(self.groupBox_2)
        self.type.setObjectName("type")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.horizontalLayout_2.addWidget(self.type)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.groupBox_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.freqModule = QtWidgets.QRadioButton(self.page)
        self.freqModule.setAutoExclusive(False)
        self.freqModule.setObjectName("freqModule")
        self.gridLayout_12.addWidget(self.freqModule, 2, 0, 1, 1)
        self.freqPhase = QtWidgets.QRadioButton(self.page)
        self.freqPhase.setAutoExclusive(False)
        self.freqPhase.setObjectName("freqPhase")
        self.gridLayout_12.addWidget(self.freqPhase, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.page)
        self.label_26.setObjectName("label_26")
        self.gridLayout_12.addWidget(self.label_26, 1, 0, 1, 2)
        self.verticalLayout_10.addLayout(self.gridLayout_12)
        self.line_8 = QtWidgets.QFrame(self.page)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_10.addWidget(self.line_8)
        self.freqEnable = QtWidgets.QCheckBox(self.page)
        self.freqEnable.setObjectName("freqEnable")
        self.verticalLayout_10.addWidget(self.freqEnable)
        self.freqWidget = QtWidgets.QWidget(self.page)
        self.freqWidget.setEnabled(False)
        self.freqWidget.setObjectName("freqWidget")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.freqWidget)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.freqMax = QtWidgets.QDoubleSpinBox(self.freqWidget)
        self.freqMax.setAlignment(QtCore.Qt.AlignCenter)
        self.freqMax.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.freqMax.setDecimals(8)
        self.freqMax.setMinimum(1e-06)
        self.freqMax.setMaximum(100000000.0)
        self.freqMax.setObjectName("freqMax")
        self.gridLayout_13.addWidget(self.freqMax, 2, 1, 1, 1)
        self.freqPoints = QtWidgets.QSpinBox(self.freqWidget)
        self.freqPoints.setAlignment(QtCore.Qt.AlignCenter)
        self.freqPoints.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.freqPoints.setMinimum(1)
        self.freqPoints.setMaximum(1000000000)
        self.freqPoints.setObjectName("freqPoints")
        self.gridLayout_13.addWidget(self.freqPoints, 3, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.freqWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName("label_27")
        self.gridLayout_13.addWidget(self.label_27, 2, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.freqWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout_13.addWidget(self.label_28, 3, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.freqWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName("label_29")
        self.gridLayout_13.addWidget(self.label_29, 1, 0, 1, 1)
        self.freqMin = QtWidgets.QDoubleSpinBox(self.freqWidget)
        self.freqMin.setAlignment(QtCore.Qt.AlignCenter)
        self.freqMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.freqMin.setDecimals(8)
        self.freqMin.setMinimum(1e-06)
        self.freqMin.setMaximum(100000000.0)
        self.freqMin.setObjectName("freqMin")
        self.gridLayout_13.addWidget(self.freqMin, 1, 1, 1, 1)
        self.verticalLayout_10.addWidget(self.freqWidget)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_15 = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setScaledContents(False)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.impulsive = QtWidgets.QRadioButton(self.page_3)
        self.impulsive.setAutoExclusive(True)
        self.impulsive.setObjectName("impulsive")
        self.verticalLayout.addWidget(self.impulsive)
        self.step = QtWidgets.QRadioButton(self.page_3)
        self.step.setAutoExclusive(True)
        self.step.setObjectName("step")
        self.verticalLayout.addWidget(self.step)
        self.line_3 = QtWidgets.QFrame(self.page_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.importButton = QtWidgets.QPushButton(self.page_3)
        self.importButton.setMaximumSize(QtCore.QSize(120, 30))
        self.importButton.setObjectName("importButton")
        self.verticalLayout.addWidget(self.importButton, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.bodeModule = QtWidgets.QRadioButton(self.page_2)
        self.bodeModule.setAutoExclusive(False)
        self.bodeModule.setObjectName("bodeModule")
        self.gridLayout_5.addWidget(self.bodeModule, 2, 0, 1, 1)
        self.bodePhase = QtWidgets.QRadioButton(self.page_2)
        self.bodePhase.setAutoExclusive(False)
        self.bodePhase.setObjectName("bodePhase")
        self.gridLayout_5.addWidget(self.bodePhase, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 1, 0, 1, 2)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.line_2 = QtWidgets.QFrame(self.page_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.bodeEnable = QtWidgets.QCheckBox(self.page_2)
        self.bodeEnable.setObjectName("bodeEnable")
        self.verticalLayout_5.addWidget(self.bodeEnable)
        self.bodeWidget = QtWidgets.QWidget(self.page_2)
        self.bodeWidget.setEnabled(False)
        self.bodeWidget.setObjectName("bodeWidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.bodeWidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.bodeMax = QtWidgets.QDoubleSpinBox(self.bodeWidget)
        self.bodeMax.setAlignment(QtCore.Qt.AlignCenter)
        self.bodeMax.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.bodeMax.setDecimals(8)
        self.bodeMax.setMinimum(1e-06)
        self.bodeMax.setMaximum(100000000.0)
        self.bodeMax.setObjectName("bodeMax")
        self.gridLayout_7.addWidget(self.bodeMax, 2, 1, 1, 1)
        self.bodePoints = QtWidgets.QSpinBox(self.bodeWidget)
        self.bodePoints.setAlignment(QtCore.Qt.AlignCenter)
        self.bodePoints.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.bodePoints.setMinimum(1)
        self.bodePoints.setMaximum(10000000)
        self.bodePoints.setObjectName("bodePoints")
        self.gridLayout_7.addWidget(self.bodePoints, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.bodeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.bodeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.bodeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 1, 0, 1, 1)
        self.bodeMin = QtWidgets.QDoubleSpinBox(self.bodeWidget)
        self.bodeMin.setAlignment(QtCore.Qt.AlignCenter)
        self.bodeMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.bodeMin.setDecimals(8)
        self.bodeMin.setMinimum(1e-06)
        self.bodeMin.setMaximum(100000000.0)
        self.bodeMin.setObjectName("bodeMin")
        self.gridLayout_7.addWidget(self.bodeMin, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.bodeWidget)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.gridLayout_3.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.previewBox = QtWidgets.QGroupBox(Dialog)
        self.previewBox.setFlat(False)
        self.previewBox.setCheckable(False)
        self.previewBox.setObjectName("previewBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.previewBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.preview = QtWidgets.QVBoxLayout()
        self.preview.setObjectName("preview")
        self.verticalLayout_2.addLayout(self.preview)
        self.gridLayout_3.addWidget(self.previewBox, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.PolesZeros = QtWidgets.QWidget()
        self.PolesZeros.setObjectName("PolesZeros")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.PolesZeros)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.zeros = QtWidgets.QLineEdit(self.PolesZeros)
        self.zeros.setObjectName("zeros")
        self.gridLayout_2.addWidget(self.zeros, 2, 1, 1, 1)
        self.poles = QtWidgets.QLineEdit(self.PolesZeros)
        self.poles.setObjectName("poles")
        self.gridLayout_2.addWidget(self.poles, 1, 1, 1, 1)
        self.gain = QtWidgets.QLineEdit(self.PolesZeros)
        self.gain.setObjectName("gain")
        self.gridLayout_2.addWidget(self.gain, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.PolesZeros)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.PolesZeros)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.PolesZeros)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.tabWidget.addTab(self.PolesZeros, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.denominator = QtWidgets.QLineEdit(self.tab_2)
        self.denominator.setObjectName("denominator")
        self.gridLayout.addWidget(self.denominator, 1, 1, 1, 1)
        self.numerator = QtWidgets.QLineEdit(self.tab_2)
        self.numerator.setObjectName("numerator")
        self.gridLayout.addWidget(self.numerator, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 2, 0, 1, 2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(10, 10, 10, 0)
        self.formLayout.setHorizontalSpacing(60)
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.name = QtWidgets.QLineEdit(Dialog)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.xMagnitude = QtWidgets.QComboBox(Dialog)
        self.xMagnitude.setObjectName("xMagnitude")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.xMagnitude)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.yMagnitude = QtWidgets.QComboBox(Dialog)
        self.yMagnitude.setObjectName("yMagnitude")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.yMagnitude)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.horizontalWidget = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.horizontalWidget.setFont(font)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.status = QtWidgets.QLabel(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.status.setFont(font)
        self.status.setText("")
        self.status.setObjectName("status")
        self.horizontalLayout.addWidget(self.status)
        self.verticalLayout_3.addWidget(self.horizontalWidget)
        self.info = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.info.setFont(font)
        self.info.setText("")
        self.info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.info.setWordWrap(True)
        self.info.setIndent(8)
        self.info.setObjectName("info")
        self.verticalLayout_3.addWidget(self.info)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setEnabled(False)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox, 0, QtCore.Qt.AlignBottom)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 3, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.type.currentIndexChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_2.setTitle(_translate("Dialog", "Output Generated"))
        self.label_7.setText(_translate("Dialog", "Output type"))
        self.type.setItemText(0, _translate("Dialog", "Frequency Response"))
        self.type.setItemText(1, _translate("Dialog", "Temporal Response"))
        self.type.setItemText(2, _translate("Dialog", "Bode"))
        self.freqModule.setText(_translate("Dialog", "|H(f)| Module"))
        self.freqPhase.setText(_translate("Dialog", "H(f)° Phase"))
        self.label_26.setText(_translate("Dialog", "Choose the output..."))
        self.freqEnable.setText(_translate("Dialog", "Custom frequency set"))
        self.label_27.setText(_translate("Dialog", "Maximum frequency"))
        self.label_28.setText(_translate("Dialog", "Number of points"))
        self.label_29.setText(_translate("Dialog", "Minimum frequency"))
        self.label_15.setText(_translate("Dialog", "Choose a famous response or import a specific input signal"))
        self.impulsive.setText(_translate("Dialog", "Impulsive Response"))
        self.step.setText(_translate("Dialog", "Step Response"))
        self.importButton.setText(_translate("Dialog", "Import Signal"))
        self.bodeModule.setText(_translate("Dialog", "|H(f)| Module"))
        self.bodePhase.setText(_translate("Dialog", "H(f)° Phase"))
        self.label_14.setText(_translate("Dialog", "Choose the output..."))
        self.bodeEnable.setText(_translate("Dialog", "Custom frequency set"))
        self.label_12.setText(_translate("Dialog", "Maximum frequency"))
        self.label_13.setText(_translate("Dialog", "Number of points"))
        self.label_11.setText(_translate("Dialog", "Minimum frequency"))
        self.previewBox.setTitle(_translate("Dialog", "Preview"))
        self.label_3.setText(_translate("Dialog", "Gain"))
        self.label_4.setText(_translate("Dialog", "Poles"))
        self.label_5.setText(_translate("Dialog", "Zeros"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PolesZeros), _translate("Dialog", "Poles and Zeros"))
        self.label.setText(_translate("Dialog", "Numerator"))
        self.label_2.setText(_translate("Dialog", "Denominator"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Polynomial"))
        self.label_8.setText(_translate("Dialog", "Name"))
        self.label_9.setText(_translate("Dialog", "Magnitude X"))
        self.label_10.setText(_translate("Dialog", "Magnitude Y"))
        self.label_6.setText(_translate("Dialog", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

