# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(282, 308)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.nameInput = QtWidgets.QLineEdit(Dialog)
        self.nameInput.setObjectName("nameInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameInput)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.xMagnitudeInput = QtWidgets.QComboBox(Dialog)
        self.xMagnitudeInput.setObjectName("xMagnitudeInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.xMagnitudeInput)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.yMagnitudeInput = QtWidgets.QComboBox(Dialog)
        self.yMagnitudeInput.setObjectName("yMagnitudeInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.yMagnitudeInput)
        self.verticalLayout.addLayout(self.formLayout)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setHorizontalSpacing(25)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.waveformsInput = QtWidgets.QComboBox(Dialog)
        self.waveformsInput.setObjectName("waveformsInput")
        self.waveformsInput.addItem("")
        self.waveformsInput.addItem("")
        self.waveformsInput.addItem("")
        self.waveformsInput.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.waveformsInput)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.groupBox_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setHorizontalSpacing(50)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.sinAmplitude = QtWidgets.QDoubleSpinBox(self.page)
        self.sinAmplitude.setMinimum(-100.0)
        self.sinAmplitude.setMaximum(100.0)
        self.sinAmplitude.setObjectName("sinAmplitude")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sinAmplitude)
        self.sinFrequency = QtWidgets.QDoubleSpinBox(self.page)
        self.sinFrequency.setMaximum(100000000.0)
        self.sinFrequency.setObjectName("sinFrequency")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sinFrequency)
        self.sinPhase = QtWidgets.QDoubleSpinBox(self.page)
        self.sinPhase.setMinimum(-180.0)
        self.sinPhase.setMaximum(180.0)
        self.sinPhase.setObjectName("sinPhase")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sinPhase)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setHorizontalSpacing(60)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.stepAmplitude = QtWidgets.QDoubleSpinBox(self.page_3)
        self.stepAmplitude.setMinimum(-100.0)
        self.stepAmplitude.setMaximum(100.0)
        self.stepAmplitude.setObjectName("stepAmplitude")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stepAmplitude)
        self.verticalLayout_5.addLayout(self.formLayout_4)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setHorizontalSpacing(60)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_9 = QtWidgets.QLabel(self.page_4)
        self.label_9.setObjectName("label_9")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.page_4)
        self.label_10.setObjectName("label_10")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.page_4)
        self.label_11.setObjectName("label_11")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.squareAmplitude = QtWidgets.QDoubleSpinBox(self.page_4)
        self.squareAmplitude.setMinimum(-100.0)
        self.squareAmplitude.setMaximum(100.0)
        self.squareAmplitude.setObjectName("squareAmplitude")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.squareAmplitude)
        self.squareFrequency = QtWidgets.QDoubleSpinBox(self.page_4)
        self.squareFrequency.setMaximum(10000000.0)
        self.squareFrequency.setObjectName("squareFrequency")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.squareFrequency)
        self.squareDuty = QtWidgets.QDoubleSpinBox(self.page_4)
        self.squareDuty.setObjectName("squareDuty")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.squareDuty)
        self.verticalLayout_6.addLayout(self.formLayout_5)
        self.stackedWidget.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setHorizontalSpacing(60)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.triangleAmplitude = QtWidgets.QDoubleSpinBox(self.page_2)
        self.triangleAmplitude.setMinimum(-100.0)
        self.triangleAmplitude.setMaximum(100.0)
        self.triangleAmplitude.setObjectName("triangleAmplitude")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.triangleAmplitude)
        self.triangleFrequency = QtWidgets.QDoubleSpinBox(self.page_2)
        self.triangleFrequency.setMaximum(10000000.0)
        self.triangleFrequency.setObjectName("triangleFrequency")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.triangleFrequency)
        self.triangleSymmetry = QtWidgets.QDoubleSpinBox(self.page_2)
        self.triangleSymmetry.setObjectName("triangleSymmetry")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.triangleSymmetry)
        self.verticalLayout_7.addLayout(self.formLayout_6)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(3)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.waveformsInput.currentIndexChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        self.stackedWidget.currentChanged['int'].connect(self.waveformsInput.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Name"))
        self.label_2.setText(_translate("Dialog", "Magnitude X"))
        self.label_3.setText(_translate("Dialog", "Magnitude Y"))
        self.label_4.setText(_translate("Dialog", "Waveforms"))
        self.waveformsInput.setItemText(0, _translate("Dialog", "Sinusoidal"))
        self.waveformsInput.setItemText(1, _translate("Dialog", "Step"))
        self.waveformsInput.setItemText(2, _translate("Dialog", "Square"))
        self.waveformsInput.setItemText(3, _translate("Dialog", "Triangle"))
        self.groupBox_2.setTitle(_translate("Dialog", "Signal Settings"))
        self.label_5.setText(_translate("Dialog", "Amplitude"))
        self.label_6.setText(_translate("Dialog", "Frequency (Hz)"))
        self.label_7.setText(_translate("Dialog", "Phase (°)"))
        self.label_8.setText(_translate("Dialog", "Amplitude"))
        self.label_9.setText(_translate("Dialog", "Amplitude"))
        self.label_10.setText(_translate("Dialog", "Frequency (Hz)"))
        self.label_11.setText(_translate("Dialog", "Duty (%)"))
        self.label_12.setText(_translate("Dialog", "Amplitude"))
        self.label_13.setText(_translate("Dialog", "Frequency (Hz)"))
        self.label_14.setText(_translate("Dialog", "Symmetry (%)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

