# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ltspice_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(606, 484)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.functionList = QtWidgets.QListWidget(Dialog)
        self.functionList.setMaximumSize(QtCore.QSize(400, 16777215))
        self.functionList.setObjectName("functionList")
        self.horizontalLayout.addWidget(self.functionList)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dataSelectionGB = QtWidgets.QGroupBox(Dialog)
        self.dataSelectionGB.setObjectName("dataSelectionGB")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dataSelectionGB)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setHorizontalSpacing(50)
        self.formLayout_2.setObjectName("formLayout_2")
        self.y = QtWidgets.QLabel(self.dataSelectionGB)
        self.y.setObjectName("y")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.y)
        self.amplitudeCB = QtWidgets.QCheckBox(self.dataSelectionGB)
        self.amplitudeCB.setObjectName("amplitudeCB")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.amplitudeCB)
        self.phaseCB = QtWidgets.QCheckBox(self.dataSelectionGB)
        self.phaseCB.setObjectName("phaseCB")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.phaseCB)
        self.yAxis = QtWidgets.QComboBox(self.dataSelectionGB)
        self.yAxis.setObjectName("yAxis")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.yAxis)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        self.verticalLayout_2.addWidget(self.dataSelectionGB)
        self.functionSettingGB = QtWidgets.QGroupBox(Dialog)
        self.functionSettingGB.setObjectName("functionSettingGB")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.functionSettingGB)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(50)
        self.formLayout.setObjectName("formLayout")
        self.yMagLabel = QtWidgets.QLabel(self.functionSettingGB)
        self.yMagLabel.setObjectName("yMagLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.yMagLabel)
        self.yMagnitude = QtWidgets.QComboBox(self.functionSettingGB)
        self.yMagnitude.setObjectName("yMagnitude")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.yMagnitude)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.functionSettingGB)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_2.addWidget(self.addButton)
        self.deleteButton = QtWidgets.QPushButton(Dialog)
        self.deleteButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_2.addWidget(self.deleteButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.okButton = QtWidgets.QDialogButtonBox(Dialog)
        self.okButton.setOrientation(QtCore.Qt.Horizontal)
        self.okButton.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 9, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.filepathLabel = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filepathLabel.sizePolicy().hasHeightForWidth())
        self.filepathLabel.setSizePolicy(sizePolicy)
        self.filepathLabel.setWordWrap(True)
        self.filepathLabel.setObjectName("filepathLabel")
        self.horizontalLayout_3.addWidget(self.filepathLabel)
        self.filepathPTE = QtWidgets.QLineEdit(Dialog)
        self.filepathPTE.setMaximumSize(QtCore.QSize(700, 16777215))
        self.filepathPTE.setReadOnly(True)
        self.filepathPTE.setObjectName("filepathPTE")
        self.horizontalLayout_3.addWidget(self.filepathPTE)
        self.browseButton = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseButton.sizePolicy().hasHeightForWidth())
        self.browseButton.setSizePolicy(sizePolicy)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout_3.addWidget(self.browseButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.loadFilePB = QtWidgets.QPushButton(Dialog)
        self.loadFilePB.setObjectName("loadFilePB")
        self.gridLayout.addWidget(self.loadFilePB, 6, 0, 1, 1)
        self.mcCheckBox = QtWidgets.QCheckBox(Dialog)
        self.mcCheckBox.setObjectName("mcCheckBox")
        self.gridLayout.addWidget(self.mcCheckBox, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.okButton.accepted.connect(Dialog.accept)
        self.okButton.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "LTSpice File Reader"))
        self.dataSelectionGB.setTitle(_translate("Dialog", "Data Selection"))
        self.y.setText(_translate("Dialog", "Y-axis"))
        self.amplitudeCB.setText(_translate("Dialog", "Amplitude"))
        self.phaseCB.setText(_translate("Dialog", "Phase"))
        self.functionSettingGB.setTitle(_translate("Dialog", "Function Settings"))
        self.yMagLabel.setText(_translate("Dialog", "Y Magnitude"))
        self.addButton.setText(_translate("Dialog", "Add"))
        self.deleteButton.setText(_translate("Dialog", "Delete"))
        self.filepathLabel.setText(_translate("Dialog", "Filepath"))
        self.browseButton.setText(_translate("Dialog", "..."))
        self.loadFilePB.setText(_translate("Dialog", "Load File"))
        self.mcCheckBox.setText(_translate("Dialog", "Montecarlo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

