# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(892, 477)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 892, 21))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menufrom_LTSpice_IV = QtWidgets.QMenu(self.menuImport)
        self.menufrom_LTSpice_IV.setObjectName("menufrom_LTSpice_IV")
        self.menuExport = QtWidgets.QMenu(self.menubar)
        self.menuExport.setObjectName("menuExport")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuAdd = QtWidgets.QMenu(self.menubar)
        self.menuAdd.setObjectName("menuAdd")
        self.menuSignal = QtWidgets.QMenu(self.menuAdd)
        self.menuSignal.setObjectName("menuSignal")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionas_Image = QtWidgets.QAction(MainWindow)
        self.actionas_Image.setObjectName("actionas_Image")
        self.actionfrom_Excel = QtWidgets.QAction(MainWindow)
        self.actionfrom_Excel.setObjectName("actionfrom_Excel")
        self.actionfrom_TransferFunction = QtWidgets.QAction(MainWindow)
        self.actionfrom_TransferFunction.setObjectName("actionfrom_TransferFunction")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionfrom_TransferFunction_2 = QtWidgets.QAction(MainWindow)
        self.actionfrom_TransferFunction_2.setObjectName("actionfrom_TransferFunction_2")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave_all = QtWidgets.QAction(MainWindow)
        self.actionSave_all.setObjectName("actionSave_all")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSenoidal = QtWidgets.QAction(MainWindow)
        self.actionSenoidal.setObjectName("actionSenoidal")
        self.actionSquare = QtWidgets.QAction(MainWindow)
        self.actionSquare.setObjectName("actionSquare")
        self.actionTriangle = QtWidgets.QAction(MainWindow)
        self.actionTriangle.setObjectName("actionTriangle")
        self.actionImpulse = QtWidgets.QAction(MainWindow)
        self.actionImpulse.setObjectName("actionImpulse")
        self.actionStep = QtWidgets.QAction(MainWindow)
        self.actionStep.setObjectName("actionStep")
        self.actionSignal = QtWidgets.QAction(MainWindow)
        self.actionSignal.setObjectName("actionSignal")
        self.actionBode = QtWidgets.QAction(MainWindow)
        self.actionBode.setObjectName("actionBode")
        self.menuFiles.addAction(self.actionOpen)
        self.menuFiles.addAction(self.actionSave)
        self.menuFiles.addAction(self.actionSave_as)
        self.menuFiles.addAction(self.actionSave_all)
        self.menuFiles.addAction(self.actionExit)
        self.menufrom_LTSpice_IV.addAction(self.actionSignal)
        self.menufrom_LTSpice_IV.addAction(self.actionBode)
        self.menuImport.addAction(self.menufrom_LTSpice_IV.menuAction())
        self.menuImport.addAction(self.actionfrom_Excel)
        self.menuExport.addAction(self.actionas_Image)
        self.menuAbout.addAction(self.actionAbout)
        self.menuSignal.addAction(self.actionSenoidal)
        self.menuSignal.addAction(self.actionSquare)
        self.menuSignal.addAction(self.actionTriangle)
        self.menuSignal.addAction(self.actionStep)
        self.menuAdd.addAction(self.menuSignal.menuAction())
        self.menuAdd.addAction(self.actionfrom_TransferFunction_2)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuAdd.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFiles.setTitle(_translate("MainWindow", "File"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.menufrom_LTSpice_IV.setTitle(_translate("MainWindow", "from LTSpice IV"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.menuAdd.setTitle(_translate("MainWindow", "Add"))
        self.menuSignal.setTitle(_translate("MainWindow", "Signal"))
        self.actionas_Image.setText(_translate("MainWindow", "as Image..."))
        self.actionfrom_Excel.setText(_translate("MainWindow", "from Excel"))
        self.actionfrom_TransferFunction.setText(_translate("MainWindow", "from TransferFunction..."))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionfrom_TransferFunction_2.setText(_translate("MainWindow", "Transfer Function"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionSave_all.setText(_translate("MainWindow", "Save all"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSenoidal.setText(_translate("MainWindow", "Sinusoidal"))
        self.actionSquare.setText(_translate("MainWindow", "Square"))
        self.actionTriangle.setText(_translate("MainWindow", "Triangle"))
        self.actionImpulse.setText(_translate("MainWindow", "Impulse"))
        self.actionStep.setText(_translate("MainWindow", "Step"))
        self.actionSignal.setText(_translate("MainWindow", "Signal"))
        self.actionBode.setText(_translate("MainWindow", "Bode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

