# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 737)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setMaximumSize(QtCore.QSize(350, 16777215))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.plotterList = QtWidgets.QListWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotterList.sizePolicy().hasHeightForWidth())
        self.plotterList.setSizePolicy(sizePolicy)
        self.plotterList.setMinimumSize(QtCore.QSize(0, 80))
        self.plotterList.setMaximumSize(QtCore.QSize(16777215, 80))
        self.plotterList.setObjectName("plotterList")
        self.verticalLayout_3.addWidget(self.plotterList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QPushButton(self.frame)
        self.addButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton, 0, QtCore.Qt.AlignHCenter)
        self.deleteButton = QtWidgets.QPushButton(self.frame)
        self.deleteButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.verticalFrame = QtWidgets.QFrame(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.verticalFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.visorView = GraphPlotterVisorView(self.verticalFrame)
        self.visorView.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visorView.sizePolicy().hasHeightForWidth())
        self.visorView.setSizePolicy(sizePolicy)
        self.visorView.setMinimumSize(QtCore.QSize(0, 300))
        self.visorView.setObjectName("visorView")
        self.verticalLayout_2.addWidget(self.visorView)
        self.verticalLayout.addWidget(self.verticalFrame)
        self.horizontalLayout_2.addWidget(self.verticalWidget)
        self.canvasList = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvasList.sizePolicy().hasHeightForWidth())
        self.canvasList.setSizePolicy(sizePolicy)
        self.canvasList.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.canvasList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.canvasList.setLineWidth(1)
        self.canvasList.setObjectName("canvasList")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.canvasList.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.canvasList.addWidget(self.page_2)
        self.horizontalLayout_2.addWidget(self.canvasList)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 21))
        self.menubar.setObjectName("menubar")
        self.menuExport = QtWidgets.QMenu(self.menubar)
        self.menuExport.setObjectName("menuExport")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuAdd = QtWidgets.QMenu(self.menubar)
        self.menuAdd.setObjectName("menuAdd")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionas_Image = QtWidgets.QAction(MainWindow)
        self.actionas_Image.setObjectName("actionas_Image")
        self.actionfrom_Excel = QtWidgets.QAction(MainWindow)
        self.actionfrom_Excel.setObjectName("actionfrom_Excel")
        self.actionfrom_TransferFunction = QtWidgets.QAction(MainWindow)
        self.actionfrom_TransferFunction.setObjectName("actionfrom_TransferFunction")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionfrom_TransferFunction_2 = QtWidgets.QAction(MainWindow)
        self.actionfrom_TransferFunction_2.setObjectName("actionfrom_TransferFunction_2")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave_all = QtWidgets.QAction(MainWindow)
        self.actionSave_all.setObjectName("actionSave_all")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSenoidal = QtWidgets.QAction(MainWindow)
        self.actionSenoidal.setObjectName("actionSenoidal")
        self.actionSquare = QtWidgets.QAction(MainWindow)
        self.actionSquare.setObjectName("actionSquare")
        self.actionTriangle = QtWidgets.QAction(MainWindow)
        self.actionTriangle.setObjectName("actionTriangle")
        self.actionImpulse = QtWidgets.QAction(MainWindow)
        self.actionImpulse.setObjectName("actionImpulse")
        self.actionStep = QtWidgets.QAction(MainWindow)
        self.actionStep.setObjectName("actionStep")
        self.actionSignal = QtWidgets.QAction(MainWindow)
        self.actionSignal.setObjectName("actionSignal")
        self.actionBode = QtWidgets.QAction(MainWindow)
        self.actionBode.setObjectName("actionBode")
        self.actionfrom_LTSpice_IV = QtWidgets.QAction(MainWindow)
        self.actionfrom_LTSpice_IV.setObjectName("actionfrom_LTSpice_IV")
        self.actionSignals = QtWidgets.QAction(MainWindow)
        self.actionSignals.setObjectName("actionSignals")
        self.actionTransfer_Function = QtWidgets.QAction(MainWindow)
        self.actionTransfer_Function.setObjectName("actionTransfer_Function")
        self.actionfrom_LTSpice_IV_2 = QtWidgets.QAction(MainWindow)
        self.actionfrom_LTSpice_IV_2.setObjectName("actionfrom_LTSpice_IV_2")
        self.actionfrom_Excel_2 = QtWidgets.QAction(MainWindow)
        self.actionfrom_Excel_2.setObjectName("actionfrom_Excel_2")
        self.actionOpen_2 = QtWidgets.QAction(MainWindow)
        self.actionOpen_2.setObjectName("actionOpen_2")
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.menuExport.addAction(self.actionas_Image)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAdd.addAction(self.actionSignals)
        self.menuAdd.addAction(self.actionTransfer_Function)
        self.menuAdd.addSeparator()
        self.menuAdd.addAction(self.actionfrom_LTSpice_IV_2)
        self.menuAdd.addAction(self.actionfrom_Excel_2)
        self.menuFile.addAction(self.actionOpen_2)
        self.menuFile.addAction(self.actionSave_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAdd.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Graphs"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.visorView.setToolTip(_translate("MainWindow", "Click and drag here"))
        self.visorView.setWhatsThis(_translate("MainWindow", "Visor View.  "))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.menuAdd.setTitle(_translate("MainWindow", "Add"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionas_Image.setText(_translate("MainWindow", "Image (.png)"))
        self.actionfrom_Excel.setText(_translate("MainWindow", "from Excel"))
        self.actionfrom_TransferFunction.setText(_translate("MainWindow", "from TransferFunction..."))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionfrom_TransferFunction_2.setText(_translate("MainWindow", "Transfer Function"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionSave_all.setText(_translate("MainWindow", "Save all"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSenoidal.setText(_translate("MainWindow", "Sinusoidal"))
        self.actionSquare.setText(_translate("MainWindow", "Square"))
        self.actionTriangle.setText(_translate("MainWindow", "Triangle"))
        self.actionImpulse.setText(_translate("MainWindow", "Impulse"))
        self.actionStep.setText(_translate("MainWindow", "Step"))
        self.actionSignal.setText(_translate("MainWindow", "Signal"))
        self.actionBode.setText(_translate("MainWindow", "Bode"))
        self.actionfrom_LTSpice_IV.setText(_translate("MainWindow", "from LTSpice IV"))
        self.actionSignals.setText(_translate("MainWindow", "Signals"))
        self.actionTransfer_Function.setText(_translate("MainWindow", "Transfer Function"))
        self.actionfrom_LTSpice_IV_2.setText(_translate("MainWindow", "from LTSpice IV"))
        self.actionfrom_Excel_2.setText(_translate("MainWindow", "from Excel"))
        self.actionOpen_2.setText(_translate("MainWindow", "Open"))
        self.actionSave_2.setText(_translate("MainWindow", "Save"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))


from plot_tool.view.plotter_visor_view import GraphPlotterVisorView

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

